const productsdata = [
    { 
     id: 1,
     url:"https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/g/q/5/-original-imahfkf6jcuhhzyb.jpeg?q=70",
     name: 'Realme', 
     gadegt:'Realme Edge 50 Fusion (Marshmallow Blue, 256 GB)  (12 GB RAM)',
     description: 'mobile',
     dumyprice:1000, 
     price: 490 ,
     catagorie:"top",
    detail:"Realme G Play 2023 3-Day Battery Unlocked Made for US 3/32GB 16MP Camera Navy Blue"},
    { 
     id: 2,
     url:"https://m.media-amazon.com/images/I/41tXf+ETfoL._SY300_SX300_.jpg", 
     name: 'OnePlus', 
     gadegt:'OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 128 GB)  (8 GB RAM)',
     description: 'mobile',
     dumyprice:1000, 
     price: 379,
     catagorie:" ",
    detail:"SAMSUNG Galaxy A35 5G A Series Cell, AMOLED Display, Advanced Triple Camera System, Expandable Storage, Rugged Design, US Version, 2024, Awesome Navy" },
    { 
    id: 3,
    url:"https://m.media-amazon.com/images/I/71SevKMKB6L._SX569_.jpg", 
    name: 'Samsung',
    gadegt:'SAMSUNG Galaxy F34 5G (Electric Black, 128 GB)  (8 GB RAM)#', 
    description: 'tab',
    dumyprice:1000, 
    price: 550 ,
    catagorie:" ",
    detail:"Google Pixel 7a - Unlocked Android Cell Phone - Smartphone with Wide Angle Lens and 24-Hour Battery - 128 GB – Charcoal"},
    { 
    id: 4,
    url:"https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/h/i/x/-original-imagyr3vfpqrpkbv.jpeg?q=70", 
    name: 'Nothing', 
    gadegt:'Nothing Phone (2a) 5G (White, 128 GB)  (8 GB RAM)',
    description: 'mobile', 
    dumyprice:1000,
    price: 500,
    catagorie:"top",
    detail:"Google Pixel 7a - Unlocked Android Cell Phone - Smartphone with Wide Angle Lens and 24-Hour Battery - 128 GB – Charcoal"},
    { 
        id: 5, 
        url:"https://rukminim2.flixcart.com/image/300/300/xif0q/tablet/0/i/l/vhu4406in-xiaomi-original-imagtz62xc2vcuca.jpeg?q=90",
        name: 'Product 5',
        gadegt:'Apple iPad (10th Gen) 64 GB ROM 10.9 inch with Wi-Fi Only (Blue)', 
        description: 'tab',
        dumyprice:1000, 
        price: 808 ,
        catagorie:"top",
        detail:"Google Pixel 7a - Unlocked Android Cell Phone - Smartphone with Wide Angle Lens and 24-Hour Battery - 128 GB – Charcoal"},
    { 
        id: 6,
        url:"https://rukminim2.flixcart.com/image/300/300/xif0q/tablet/r/4/m/-original-imagj72vqsfqgzpf.jpeg?q=90", 
        name: 'Product 6', 
        gadegt:'SAMSUNG Galaxy Tab A7 LTE 3 GB RAM 32 GB ROM 10.4 inch with Wi-Fi+4G Tablet (Silver)',
        description: 'tab', 
        dumyprice:1000,
        price: 760 ,
        catagorie:"top",
        detail:"Google Pixel 7a - Unlocked Android Cell Phone - Smartphone with Wide Angle Lens and 24-Hour Battery - 128 GB – Charcoal"},
    { 
        id: 7,
        url:"https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/v/f/d/-original-imagpgx4g2m63gfh.jpeg?q=70", 
        name: 'Pixel', 
        gadegt:'Google Pixel 8 Pro (Bay, 128 GB)  (12 GB RAM)',
        description: 'mobile',
        dumyprice:1000, 
        price: 848,
        catagorie:"offer",
        detail:"Google Pixel 7a - Unlocked Android Cell Phone - Smartphone with Wide Angle Lens and 24-Hour Battery - 128 GB – Charcoal" },
    { 
        id: 8,
         url:"https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/z/8/k/zeb-duke-2-wireless-headphone-with-mic-32-h-playback-call-original-imagg43pf6mk6arg.jpeg?q=70",
         name: 'Product 8', 
         gadegt:'boAt Rockerz 450 w/ 40mm Drivers, 15 HRS Playback, Soft Padded Earcups Bluetooth Headset  (Luscious Black, On the Ear)',
         description: 'Accessories', 
         dumyprice:1000,
         price: 558,
         catagorie:"offer",
         detail:"Google Pixel 7a - Unlocked Android Cell Phone - Smartphone with Wide Angle Lens and 24-Hour Battery - 128 GB – Charcoal" },
    { 
        id: 9,
        url:"https://rukminim2.flixcart.com/image/612/612/kr83ukw0/power-bank/w/5/6/power-bank-plm13zm-mi-original-imag52az6xpcvjdk.jpeg?q=70", 
        name: 'Powerbank', 
        gadegt:'boAt 20000 mAh 22.5 W Power Bank  (Burgundy, Lithium Polymer, Fast Charging, Quick Charge 3.0, Power Delivery 3.0 for Mobile, Tablet)',
        description: 'Accessories',
        dumyprice:1456 ,
        price: 999,
        catagorie:"offer",
        detail:"Google Pixel 7a - Unlocked Android Cell Phone - Smartphone with Wide Angle Lens and 24-Hour Battery - 128 GB – Charcoal" },
    { 
        id: 10, 
        url:"https://rukminim2.flixcart.com/image/612/612/xif0q/battery-charger/o/l/s/-original-imagw6w3q7xp7fq4.jpeg?q=70",
        gadegt:'HOMEMO 80 W SuperVOOC 6 A Mobile Charger with Detachable Cable  (for Oneplus 12 12R 11 10 Pro 9 10T 10R 8T 8 7T 7 6T 9R Nord 3/2 2T CE, Cable Included)',
        name: 'Charger', 
        description: 'Accessories', 
        dumyprice:1000,
        price: 888,
        catagorie:" ",
        detail:"Google Pixel 7a - Unlocked Android Cell Phone - Smartphone with Wide Angle Lens and 24-Hour Battery - 128 GB – Charcoal" },
];

module.exports = productsdata;
 
